import type { Metadata } from "next";

import "bootstrap/dist/css/bootstrap.min.css";
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
import "../public/vendor/fontawesome-6.7.2/css/all.css";
// import "../public/css/fontawesome.css";
import "../public/css/themify-icons.css";
import "../public/css/animate.css";
import "../public/css/cursor.css";
import "../public/css/custom-font.css";
import "../public/css/custom.css";
import "../public/css/main.css";
import Header from "./_components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="body_wrap sco_agency">
          <Header />
          <main className="page_content">{children}</main>
        </div>
      </body>
    </html>
  );
}
